src/employee/urls.py
from django.urls import include, path
from . import views

urlpatterns = [
    path('', views.EmployeeListView.as_view(), name='employee_changelist'),
    path('add/', views.EmployeeCreateView.as_view(), name='employee_add'),
    path('<int:pk>/', views.EmployeeUpdateView.as_view(), name='employee_change'),
    path('ajax/load-designations/', views.load_designations, name='ajax_load_designations'),
    path('ajax/load-unitnames/', views.load_unitnames, name='ajax_load_unitnames'), # <-- this one here
]

src/myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(pattern_name='employee_changelist'), name='home'),
    path('employee/', include('employee.urls')),
]

src/employee/models.py
from django.db import models

class Office(models.Model):
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name

class Unitname(models.Model):
    office = models.ForeignKey(Office, on_delete=models.CASCADE)
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name

class Department(models.Model):
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name

class Designation(models.Model):
    department = models.ForeignKey(Department, on_delete=models.CASCADE)
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name

class Employee(models.Model):
    name        = models.CharField(max_length=100)
    birthdate   = models.DateField(null=True, blank=True)
    office      = models.ForeignKey(Office, on_delete=models.SET_NULL, null=True)
    unitname    = models.ForeignKey(Unitname, on_delete=models.SET_NULL, null=True)
    department  = models.ForeignKey(Department, on_delete=models.SET_NULL, null=True)
    designation = models.ForeignKey(Designation, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return self.name

src/employee/forms.py
from django import forms
from .models import Employee, Designation,Unitname

class EmployeeForm(forms.ModelForm):
    class Meta:
        model = Employee
        fields = ('name', 'birthdate','office', 'unitname','department', 'designation')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['designation'].queryset = Designation.objects.none()
        self.fields['unitname'].queryset = Unitname.objects.none()


        if 'department' and 'office' in self.data:
            try:
                department_id = int(self.data.get('department'))
                office_id = int(self.data.get('office'))
                self.fields['designation'].queryset = Designation.objects.filter(department_id=department_id).order_by('name')
                self.fields['unitname'].queryset = Unitname.objects.filter(office_id=office_id).order_by('name')
            except (ValueError, TypeError):
                pass  # invalid input from the client; ignore and fallback to empty Designation queryset
        elif self.instance.pk:
            self.fields['designation'].queryset = self.instance.department.designation_set.order_by('name')
            self.fields['unitname'].queryset = self.instance.office.unitname_set.order_by('name')

src/employee/views.py
from django.shortcuts import render
from django.views.generic import ListView, CreateView, UpdateView
from django.urls import reverse_lazy
from .models import Employee, Designation,Unitname
from .forms import EmployeeForm


class EmployeeListView(ListView):
    model = Employee
    context_object_name = 'employee'


class EmployeeCreateView(CreateView):
    model = Employee
    form_class = EmployeeForm
    success_url = reverse_lazy('employee_changelist')


class EmployeeUpdateView(UpdateView):
    model = Employee
    form_class = EmployeeForm
    success_url = reverse_lazy('employee_changelist')


def load_designations(request):
    department_id = request.GET.get('department')
    designations = Designation.objects.filter(department_id=department_id).order_by('name')
    return render(request, 'employee/designation_dropdown_list_options.html', {'designations': designations})

def load_unitnames(request):
    office_id = request.GET.get('office')
    unitnames = Unitname.objects.filter(office_id=office_id).order_by('name')
    return render(request, 'employee/unitname_dropdown_list_options.html', {'unitnames': unitnames})

src/employee/templates/employee/designation_dropdown_list_options.html
<option value="">---------</option>
{% for designation in designations %}
<option value="{{ designation.pk }}">{{ designation.name }}</option>
{% endfor %}

src/employee/templates/employee/employee_form.html
{% extends 'base.html' %}

{% block content %}

  <h2>Employee Form</h2>

  <form method="post" id="employeeForm" data-unitnames-url="{% url 'ajax_load_unitnames' %}" novalidate>
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <button type="submit">Save</button>
    <a href="{% url 'employee_changelist' %}">Nevermind</a>
  </form>

  <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script>
    $("#id_office").change(function () {
      var url = $("#employeeForm").attr("data-unitnames-url");
      var officeId = $(this).val();

      $.ajax({
        url: url,
        data: {
          'office': officeId
        },
        success: function (data) {
          $("#id_unitname").html(data);
        }
      });

    });
  </script>
  <script>
    $("#id_department").change(function () {
      var url = $("#employeeForm").attr("data-designations-url");
      var officeId = $(this).val();

      $.ajax({
        url: url,
        data: {
          'department': departmentId
        },
        success: function (data) {
          $("#id_designation").html(data);
        }
      });

    });
  </script>

{% endblock %}

src/employee/templates/employee/employee_list.html
{% extends 'base.html' %}

{% block title %}Human Resources Module{% endblock %}

{% block content %}
  <h2>Human Resources Module » Employee Management</h2>

  <p>
    <a href="{% url 'employee_add' %}">Add person</a>
  </p>

  <table border="1">
    <thead>
      <tr>
        <th>Name</th>
        <th>Birthdate</th>
        <th>Office Name</th>
        <th>Unit</th>
        <th>Department</th>
        <th>Designation</th>

      </tr>
    </thead>
    <tbody>
      {% for person in employee %}
        <tr>
          <td><a href="{% url 'employee_change' person.pk %}">{{ person.name }}</a></td>
          <td>{{ person.birthdate }}</td>
          <td>{{ person.office.name }}</td>
          <td>{{ person.unitname.name }}</td>
          <td>{{ person.department.name }}</td>
          <td>{{ person.designation.name }}</td>
        </tr>
      {% empty %}
        <tr>
          <td colspan="4">No person in the database. <a href="{% url 'employee_add' %}">Add the first person</a>.</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>

{% endblock %}

src/employee/templates/employee/unitname_dropdown_list_options.html
<option value="">---------</option>
{% for unitname in unitnames %}
<option value="{{ unitname.pk }}">{{ unitname.name }}</option>
{% endfor %}

src/templates/base.html
<!doctype html>
<html lang="en-us">
  <head>
    <meta charset="utf-8">
    <title>{% block title %}Simple ERP{% endblock %}</title>
    <style type="text/css">
      .errorlist {
        margin: 0;
        padding: 0;
      }
      .errorlist li {
        list-style: none;
        font-size: 90%;
        color: red;
      }
      .errorlist ~ input,
      .errorlist ~ select {
        border-color: red;
      }
    </style>
  </head>
  <body>
    <h1>Simple ERP</h1>
    <hr>
    {% block content %}
    {% endblock %}
  </body>
</html>